### PR TITLE
Launching the vite server will always open the app with appCache=false 

### LINKED ISSUE #1073: Make it so that launching the vite server will always open the app with appCache=false
Since it's a developer server, this would be helpful especially to new devs -- the parameter turns on bypassing of the appCache.

The preview (which builds the app) should be opened without the appCache bypass.

### PR DESCRIPTION
**Pull request by amitpanwar789**
Fixes #1073 
I have modified open option of vite.config.js file from "www/index.html" to "www/index.html?appCache=false"

I have done basic UI tests as maintained in contributing.md and all were passed successfully.
@Jaifroid can you please review it.

### CODE REVIEW

**Comment by Jaifroid** [comment]
Oh, you need to update the branch (see button below).

**Comment by amitpanwar789** [comment]
Done 👍

**Comment by Jaifroid** [comment]
OK merging now.

**Comment by Jaifroid** [comment]
Thank you for the PR, short but sweet!

**Pull request merged**
