### PR TITLE
Add prefix checking before displaying list of matched articles

### PR DESCRIPTION
**Pull request by zengchu2**
Attempt to address the issue described in issue #184 .

Add an early return if either the follow conditions holds:

- The search prefix input box is empty. (Which prevents loading search result after redirecting)
- The dirEntry array is non-empty and is not the result from latest prefix search. (Will handle the empty array in the origin code)

### CODE REVIEW

**Comment by zengchu2** [comment]
Thanks for the hints in addressing this issue. 

I managed to use the `latestUserAsynAction` as the state to store user's latest action that might cause false displayed. I compare the state to perform early return in `readArticle` and `searchDirEntriesFromPrefix` since these are the two callbacks that may cause false displays. 

The only problem I found while testing is after searching and clicking an article, the search result might come back too fast and block the action of going to the clicked article but I am assuming this rarely happens.

**Comment by mossroy** [comment]
@zengchu2 : do you intend to finalize this PR?

**Comment by kelson42** [comment]
No feedback from the developer. I think this PR will have to be closed or finished by someone else.

**Comment by mossroy** [comment]
Closing this PR. The branch should be kept because I think the implementation was on the right track anyway

**Pull request closed without merging**
