### PR TITLE
Prepare source code for future version 3.4

### PR DESCRIPTION
**Pull request by mossroy**

### CODE REVIEW

**Comment by mossroy** [comment]
I initially forgot to update app.js, which properly failed the build, as expected, with a meaningful message: thanks for that @Jaifroid !

**Review by Jaifroid — APPROVED** [review]
Looks good! Maybe we should try to automate updating these files somehow!

**Comment by mossroy** [comment]
> Looks good! Maybe we should try to automate updating these files somehow!

Probably.
More generally, I think we should try to release more often, if we can, following the https://en.wikipedia.org/wiki/Release_early,_release_often philosophy.
It would push us to automate everything that can be automated, which would be good if one day we have a critical bug to solve quickly, and also avoids human errors. Publishing on stores might be complicated to automate, but if it's the only manual step that remains, it would already be great.
It would also show users that the project is alive

**Comment by Jaifroid** [comment]
OK, happy with that. I have #762 for the Edge Store. Last time I checked (a week ago or so), the API was still in private testing. I imagine the other stores have API endpoints for upload and release.

**Pull request merged**
