### PR TITLE
Remove unused removeDuplicateTitlesInDirEntryArray() #491

### LINKED ISSUE #491: Remove unused functions
As per #488, there is an unused function `removeDuplicateTitlesInDirEntryArray` in `util.js`, and also a corresponding unit test. Once that PR is approved, we should remove these. It may be worth checking to see if there are further unused functions as part of any PR.

### PR DESCRIPTION
**Pull request by kelson42**
Fix #491

### CODE REVIEW

**Comment by Jaifroid** [comment]
@kelson42 Are you happy to merge this?

**Comment by kelson42** [comment]
@Jaifroid I have no clue what this PR is about. Don't really understand why you ask me.

**Comment by Jaifroid** [comment]
Ah, I thought it was your PR! You asked us to review, and I think we've both approved. But I'll merge it now.

**Comment by kelson42** [comment]
@Jaifroid You are right, sorry, I'm ready for the bed ;) Thx for the merge.

**Pull request merged**
