### PR TITLE
Add badges to the README.md

### PR DESCRIPTION
**Pull request by kelson42**

### CODE REVIEW

**Comment by Jaifroid** [comment]
Could they be placed either at the very top of the README or at the very bottom? They look a bit odd in the middle of the page, but if you've standardized that position across all kiwix repos, that's OK by me.

**Comment by kelson42** [comment]
@Jaifroid I have indeed standardised a bit this presentation. To me they are important, but not more important than the explanation about what does the tool. This is why they are put just after the introduction. But, this is pretty much a subjective thing, I agree.

**Comment by Jaifroid** [comment]
@kelson42 OK.

**Comment by Jaifroid** [comment]
Whoops, sorry, meant to comment on the other PR!

**Pull request merged**
