### PR TITLE
Add a CSP to allow WASM in Chromium extensions

### LINKED ISSUE #751: WASM compilation is disabled by default in Chromium extensions
The decompressor API is red and its status is "Error loading ZSTD decompressor!".
In the browser console :

> Could not instantiate any ZSTD decoder! RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
> at A (zstddec-wasm.js:15)
> at zstddec-wasm.js:18

And nothing works afterwards.

It comes from a CSP applied on Chromium extensions (not on Firefox extensions), for security reasons.
It can be overridden by adding a line in manifest.json, see https://stackoverflow.com/questions/48523118/wasm-module-compile-error-in-chrome-extension . It seems to work with both `unsafe-eval` or `wasm-eval`, and does not seem to annoy Firefox.

Is it risky to do that?
Should we use `unsafe-eval` (that probably works with all versions of Chromium, but opens more security risks) or `wasm-eval` (that opens less security risks, but might not work with all versions of Chromium)?

### PR DESCRIPTION
**Pull request by mossroy**
Fixes #751

### CODE REVIEW

**Comment by mossroy** [comment]
The UI test now fail on edge (instead of edge44 this morning for #750, where edge was passing).
It's always the "Error ECONNRESET: socket hang up" symptom

**Comment by Jaifroid** [comment]
Now it's firefox45 failing with ECONNRESET... (I just re-ran tests). Sign.

**Comment by Jaifroid** [comment]
Tests passing now. Is it not necessary to trap any potential error with unsafe-wasm (as opposed to unsafe-eval), or do older browsers just ignore it? Also, I'm wondering why our fallback doesn't kick in if the Promise fails (without unsafe-wasm)... However, I haven't tested. I'll try to test on Edge Chromium shortly to be sure this won't block release.

**Comment by Jaifroid** [comment]
I've now tested on Edge 93.0, and the unpacked extension based on this PR runs the WASM version without complaining. So as far as I am concerned, this can be merged. Do we need to do anything about pre-2017 Chromium?

**Review by Jaifroid — APPROVED** [review]

**Comment by mossroy** [comment]
I realize I did not commit the right value : shame on me.
This PR was meant to use `unsafe-eval` (supported by all browsers) instead of `wasm-eval` (supported by chromium-based browsers since 2018). Switching to `wasm-eval` is for #752
Will fix

**Comment by Jaifroid** [comment]
No problem, I'll test this version. The only thing is we need to be sure the Stores will allow extensions with unsafe-eval, though I guess we could always try and revert to usafe-wasm if the Chrome and/or Edge stores refuse.

**Comment by Jaifroid** [comment]
Sorry, I meant *wasm-eval

**Comment by Jaifroid** [comment]
Working fine in dev mode with `unsafe-eval`.

image

**Comment by mossroy** [comment]
I had a look at why our javascript code does not gracefully fallback to ASM in this case.
In fact, it does trap the error with WASM, and tries to fallback to ASM.
But if you look inside zstddec-asm.js, you see that it tries to load a file zstddec-asm.wasm (that does not exist) if WebAssembly is supported by the browser. So I suppose it somehow calls the eval function that is forbidden by CSP

**Comment by Jaifroid** [comment]
Oh, OK. Strange. I wonder if we need another compile flag to prevent that happening, something that says "use ASM.JS only". I'll see if there's an obvious flag in the settings.

**Comment by Jaifroid** [comment]
Possibly we could try `DYNAMIC_EXECUTION=0`. See https://github.com/emscripten-core/emscripten/blob/main/src/settings.js#L1184. Description below seems to fit:

```
// When set to 0, we do not emit eval() and new Function(), which disables some functionality
// (causing runtime errors if attempted to be used), but allows the emitted code to be
// acceptable in places that disallow dynamic code execution (chrome packaged app,
// privileged firefox app, etc.). Pass this flag when developing an Emscripten application
// that is targeting a privileged or a certified execution environment, see
// Firefox Content Security Policy (CSP) webpage for details:
// https://developer.mozilla.org/en-US/Apps/Build/Building_apps_for_Firefox_OS/CSP
// When this flag is set, the following features (linker flags) are unavailable:
//  --closure 1: When using closure compiler, eval() would be needed to locate the Module object.
//  -s RELOCATABLE=1: the function Runtime.loadDynamicLibrary would need to eval().
//  --bind: Embind would need to eval().
// Additionally, the following Emscripten runtime functions are unavailable when
// DYNAMIC_EXECUTION=0 is set, and an attempt to call them will throw an exception:
// - emscripten_run_script(),
// - emscripten_run_script_int(),
// - emscripten_run_script_string(),
// - dlopen(),
// - the functions ccall() and cwrap() are still available, but they are restricted to only
//   being able to call functions that have been exported in the Module object in advance.
// When set to -s DYNAMIC_EXECUTION=2 flag is set, attempts to call to eval() are demoted
// to warnings instead of throwing an exception.
// [link]
var DYNAMIC_EXECUTION = 1;
```

**Comment by mossroy** [comment]
Yes, it's certainly worth testing!

**Comment by Jaifroid** [comment]
Drat, we already compile with `DYNAMIC_EXECUTION=0`!!!!! So I wonder why we're getting this error.

**Comment by Jaifroid** [comment]
I wonder if the setting `--closure 1` overrides or conflicts with disabling dynamic execution.

**Comment by Jaifroid** [comment]
I recompiled the ZSTD wasm version with `--closure 0`, but unfortunately it still blocks WASM loading when I remove the `unsafe-eval` in the CSP. I could keep hunting for settings that might help, or we could go ahead wiht `unsafe-eval` and see if it gets into the Stores? We could probably remove eval code ourselves from the WASM js, but then we'd have a non-reproducible compile (at least not without adding extra steps to the helper scripts). We could also disable the testing/fallback in the WASM javascript loader, which would have the same disadvantage, and would mean that Chromium extensions would always use ASM.js instead of WASM (which would be a shame, though would have no direct impact on the end user).

**Comment by mossroy** [comment]
OK. Maybe we should merge this PR, release v3.2.0 and investigate improvements afterward, in #752
The security risk is there, but appears to be very low in our case.

**Comment by Jaifroid** [comment]
Agreed.

**Pull request merged**
