### PR TITLE
Corrected the form height in `Display Settings`.

### PR DESCRIPTION
**Pull request by ankur12-1610**
Signed-off-by: ankur12-1610 <anknerd.12@gmail.com>

Fixes: #776

Before:
145025407-1837f3e7-3420-4c3b-8a7f-02437f3dbbb9
145025669-2d464238-cd79-44db-a92a-2bfae8a78c18

After:
light-solved
dark-solved

### CODE REVIEW

**Comment by ankur12-1610** [comment]
I have changed the `www/css/app.css` file and to solve this issue I had two options:
- To increase the form height.
-  To remove the form height so that bootstrap can assign the height by default.

I opted for the second option and if form height was specified for any specific reason, it can be changed and increased :)

**Comment by Jaifroid** [comment]
@ankur12-1610 Thank you very much! It's looking good. Could you let me know if you've tested it on more than one browser? Ideally Chromium (Chrome or Edge), Firefox, and IE11 (thought IE11 is optional, don't worry if you don't have access to it).

**Comment by ankur12-1610** [comment]
> @ankur12-1610 Thank you very much! It's looking good. Could you let me know if you've tested it on more than one browser? Ideally Chromium (Chrome or Edge), Firefox, and IE11 (thought IE11 is optional, don't worry if you don't have access to it).

@Jaifroid I tested it on Chromium and Firefox. I don't have IE11 so I couldn't test it:sweat_smile:.

**Comment by Jaifroid** [comment]
OK, I'll test on IE and get back to you.

**Comment by ankur12-1610** [comment]
> OK, I'll test on IE and get back to you.

Thanks :)

**Review by Jaifroid — APPROVED** [review]
Thank you @ankur12-1610 . I've tested this with IE11 and Edge (Chromium), and it works fine at large and very narrow screen widths.

**Comment by Jaifroid** [comment]
As there is only one commit, there is no need to squash. @ankur12-1610, have you completed your tests? If so, I can merge it for you.

**Comment by mossroy** [comment]
I like when removing code solves issues.
I did not test, but you can merge

**Comment by ankur12-1610** [comment]
> As there is only one commit, there is no need to squash. @ankur12-1610, have you completed your tests? If so, I can merge it for you.

Yeah I ran the tests and all of them passed.

**Pull request merged**
