### PR TITLE
Remove dummy article

### PR DESCRIPTION
**Pull request by Jaifroid**
@mossroy I have now applied the changes from Kiwix JS Windows that remove dependency on dummyArticle and void the iframe using document.open(), write() and close(). Changes are in the Remove-dummyArticle branch on which this PR is based.

PR is for testing, not yet for merging.

As explained yesterday, to make this code work, it is necessary (since we are not extracting scripts from the ZIM) to neutralize active JavaScript that otherwise gets executed on page load, and causes an unhandled exception.

The culprit here is the extra JavaScript that has been injected into Wikimedia Mobile-style ZIMs to enable the opening and closing of section headers with a click. Unnecessarily IMHO, this JavaScript relies on jQuery (it could easily be rewritten not to require jQuery). So we have to neutralize it unless we want to attach jQuery to every html page pulled from the ZIM. I'm not convinced that these JavaScript routines should be hard-coded in the ZIM -- they should be injected by the client IMHO. Maybe @kelson42  can comment on why this functionality is hard-coded in the mobile-style ZIMs rather than provided by each client.

Anyway, once we neutralize those JavaScript blocks and the open-close toggles, and remove the injected class ('client-js') that has been added to the html tag of every page, we can now use this standard open-write-close method to inject the html into the iframe. I believe it solves a lot of the problems we were seeing by injecting the html using innerHTML (which doesn't execute the JavaScript, but also prevents some other things from rendering properly). Plus we squash #347 by not loading dummyArticle into the iframe.

It is quite likely that this code won't work initially in Service Worker mode, because the code for neutralizing the JavaScript is currently applied only inside a `if (contentInjectionMode === 'jquery')` block. Some of those should, I believe, be applied to both injection modes unless Service Worker mode is correctly pulling scripts from the ZIM. I leave that to you to test.

This code is tested on: IE11, Edge, Firefox ESR, Firefox Quantum and FFOS emulator. I have not tested on Chrome yet.

Please test thoroughly!

### CODE REVIEW

**Comment by kelson42** [comment]
@Jaifroid It looks like you are disturbed by the feature which allows to open/close section with a click on Wikipedia based ZIM files (mobile version). This is indeed a feature of the content and I do not see why this should be handle outside the content (by the reader) as this is a specificity of the content/ZIM. We will have more and more ZIM file with sophisticated javascript in them (also based on jquery). If that is a problem with Kiwix-js, then we should really find a way to improve Kiwix-js to avoid that.

**Comment by Jaifroid** [comment]
Sorry, @kelson42 , I'm not disturbed by it, I just have to work around it, because Kiwix JS doesn't currently support extracting and executing JavaScript from the ZIM. The script in question has this comment:

`// this function is to be able to open/close section in mobile version since the code from wiki meant to do that doesn't work`

So I thought it must have been added during scraping, and therefore not in the original HTML. It seemed like a functionality that the client should provide (and could easily provide). Clicking on sections that have the openToggle onclick event currently causes Kiwix JS to crash, but so does loading any page from such a ZIM if we do it in a way that executes JavaScript, because of the use of jQuery in that script. This is clearly a limitation of our client, but we have to work around it for now.

Good to know that the roadmap for the ZIM includes dynamic functionality -- a good reason for getting JavaScript working in Kiwix JS. Personally, I'm not a fan of jQuery, but that's down to personal coding style and history.

**Comment by Jaifroid** [comment]
I've been doing a bit of reading on the merits of inserting HTML using .innerHTML vs document.write(). Main difference is that with the former, as I noted above, inline scripts do not execute, whereas with the latter they do. See https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML . Document.write() doesn't work in XHTML documents that are served as XML (rarely the case, and not relevant to Kiwix JS, I think). Note that I found this warning on the above page, with regard to the use of innerHTML in browser extensions, and thought it might be relevant:

image

**Comment by Jaifroid** [comment]
Following above discussion, and since we cannot use the supplied routine, I've implemented functionality for opening and closing section headers. Like the supplied routine, this includes the ability to open the section (if it is closed) that contains the target of any footnote, endnote or other form of note that has been clicked on (the section is derived from the target). These are the reasons why we cannot use the supplied routine in Kiwix JS:

* Due to the Content Security Policy, Firefox OS does not support use of JavaScript in inline HTML, e.g. in the `onclick = toggleOpenSection();` which is hard-coded in the mobile-style ZIM's supplied routine;

* Even if we decide not to support FFOS at some point in the future, we would have to extract or inject jQuery into every page taken from the ZIM, which seems wasteful for a few lines of code;

* The supplied routine is buggy, and does not work on ZIMs that contain reference sections with different ID's than the hard-coded id="References". E.g. several WikiMed articles have reference sections with id="Notes" and even id="Footnotes" (sometimes in addition to id="References"), and potentially others. A more generic routine is needed, and ideally one that doesn't use inline JavaScript but attaches the onclick event using addEventListener.

I've written a generic version that doesn't need jQuery here: https://github.com/kiwix/kiwix-js/pull/353/files#diff-bca463ed8ccf5e2058dfe307a95e8501R860 . No doubt it can be improved, but it's suitable for use in our client and doesn't rely on the inline onclick event in the HTML. It is tested on FFOS, IE11, Edge and Firefox with a range of ZIMs.

Note that a page is started with all headings open, rather than closed, as I believe it could be disorientating to users not used to having all headers closed. This could easily be changed, say, just for ZIMs that have a mobile style. A good ZIM to test this routine on is the latest WikiMed. @Mossroy, I completely understand if you don't want to use such a routine in Kiwix JS, but I'd be grateful if you could try it out and let me know of any problems. I'll probably use it in Kiwix JS Windows, but I wrote it out of interest, and as a challenge.

**Comment by Jaifroid** [comment]
That's a great summary, @Mossroy. I'm very happy to separate out the issues. One led to another as logical consequences of each other, which is why they got pushed into this PR.

I think I'll keep this branch as a repository of ideas and port the issues into different branches.

Yes, we can start with `document.write()`, though I think it very quickly requires neutralization of JavaScript on the page at least until we have implemented #152.

**Comment by Jaifroid** [comment]
Closing. See #341 for continuation.

**Pull request closed without merging**
