### PR TITLE
Remove vertical scrollbar

### LINKED ISSUE #566: There is a vertical scrollbar since bootstrap 4
It did not show up in previous versions.

I'm not talking about a vertical scrollbar inside the iframe (which is normal), but one on the whole window.
It appears on both Firefox and Chromium.

### PR DESCRIPTION
**Pull request by Jaifroid**
Fixes #566.

### CODE REVIEW

**Comment by Jaifroid** [comment]
Hmm, I think that's a different issue which is not related to #566 as far as I can tell. This PR is about the extra uselesss scrollbar. What you're reporting is a version of a longstanding issue covered (perhaps indirectly) by #120, #337 or #386. I've checked on master, and the cutoff (worse on older ZIMs, better on recent ZIMs of type "maxi") is the same before and after this PR. The only difference is that the extra vertical scrollbar shows before this PR, but that extra scrollbar doesn't help to scroll the iframe further down beyond the cutoff (it is a completely useless scrollbar). So I think this PR does address the reported issue, and we should fix the longstanding issue of content cut off by the bottom bar as part of #523, or else in a specific PR if you think there's a different viable solution. (You may remember we once had to add some `<br />` padding to the end of the content to work around this issue in jQuery mode, but that doesn't work in SW mode, and we weren't ever satisfied with that kludge...).

**Comment by Jaifroid** [comment]
PS The extra scrollbar is produced by the "search-article" div, which has no bearing on the iframe, and therefore on the content in the iframe.

**Comment by Jaifroid** [comment]
Hey @mossroy , I wondered if you had further thoughts about this PR (reading my comments above). As I say there, I don't think the issue you report pertains to this PR, which is merely about removing the extra vertical scrollbar. The extra scrollbar in question doesn't appear to govern the amont of content shown in the iframe, evinced by the fact that you can't actually scroll it at all.

**Comment by mossroy** [comment]
Sorry that I did not have the time to work on that.

Before the bootstrap upgrade, it' true that we already had issues with the bottom content.
But having some content behind the bottom bar is not the same as having some content not visible at all.
When it's behind the bottom bar, it's still mostly visible as the bottom bar is transparent (even if links can not be clicked). And the content can become completely available if we remove (or hide) the bottom bar.
With this PR, the content seems lost to me.
Using `overflow: hidden` hides the content that does not fit (see examples in https://developer.mozilla.org/fr/docs/Web/CSS/overflow )

But, after testing a bit more, I noticed that this issue was already present before the bootstrap upgrade, a least on Chrome (in SW mode). So it might not be a regression caused by the upgrade.

**Comment by mossroy** [comment]
@Jaifroid : I suggest to close this PR for now, as both of us did not have the time to work on it in the last month

**Pull request closed without merging**
