### PR TITLE
Fix for dead object #361 and history regression #366

### PR DESCRIPTION
**Pull request by Jaifroid**
PR of combined changes from #366 (incorporating fix for #361 already in #366). See comment there.

### CODE REVIEW

**Comment by Jaifroid** [comment]
Whoops, I see there's a typo in the commit title (objexts instead of objects). I'll correct before merge. More haste, less speed. Also, @mossroy , looks like this PR has failed one of the integration tests...? Did I do something wrong?

**Comment by Jaifroid** [comment]
@mossroy , I've pushed a commit to this PR that ensures the iframe is run in Standards mode, not in Quirks Mode. The problem was that we were not writing a DOCTYPE declaration to the iframe. I'm not sure if this is because the ZIM articles don't include a doctype or because we accidentally exclude it. The added code is simply this:

`articleContentDocument.write("<!DOCTYPE html>"); // Ensures browsers parse iframe in Standards mode` 

And I see that this fixes the integration tests too.

**Comment by Jaifroid** [comment]
Could it be that pesky onload event for when the user changes mode? It's just a wild guess.
Or maybe pushing the doctype before the rest of the document is an issue? I kind of doubt it, but you never know with JavaScript and the DOM...

**Comment by Jaifroid** [comment]
Another quick thought: might the exception produced in the iframe by the lack of jQuery be causing problems? Does the regression only happen with recent Wikimedia ZIMs? On every such article I get the message in screenshot below in Console. Until we can extract the JavaScript (see #152 ) we should probably neutralize this.

image

**Comment by mossroy** [comment]
The regression is certainly not related to the `'$' is not defined` console errors : this appears after the page is loaded (onload event), after the CSS and JS fail to load.
It appears on old ZIM files too (the Ray Charles one, for example). It does not seem to be related to the onload event we add (because the issue is still there if I comment this code).

I tested with the .innerHTML method (commit aa2c65d1785b54e1a3c987adf9e060a14cce0e89 of branch Fix-history-back-regression) : it works fine (the CSS HTTP requests are trapped by the ServiceWorker in all cases).

I suspect that the document.write method does not set a source that is inside the scope of the ServiceWorker (or something similar). I need to check if there is a way to do so.
Else we might switch (again) the method ;-)

**Comment by Jaifroid** [comment]
Hmm, OK I've pushed a branch with the latest version of the innerHTML fix for testing here:

**Comment by mossroy** [comment]
Yes, it would be better to add `<meta charset="utf-8">` in the head section. I would also advise to add a title there, like `placeholder where articles will be injected`.

Regarding the document.write method, I managed to workaround the problem on Chrome, by setting a src to the iframe tag (in index.html), pointing to an empty html file like your article.html. But it only seems to work on Chrome, not on Firefox.

Regarding the innerHTML method, I'd be fine to finally choose it, but there are 2 issues : 
- The way to copy the CSS classes of the HTML tag is not generic. For example, some CSS styles might be applied with the `style` attribute (without referring to a CSS class), and there might be other attributes too. It would be better to find a way to copy all attributes of this tag, in order to be more generic (NB : why are you applying the CSS styles to the body tag instead of the htm tag?)
- It might not be accepted by the extension reviews. As you already pointed, Chrome might accept (see https://wiki.mozilla.org/Add-ons/Reviewers/Guide/Reviewing#Step_2:_Automatic_validation), but Mozilla will probably not (see the warning in the middle of https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML). But we might submit it to find out, we don't have much to loose...

I tested this innerHTML method only quickly with Firefox 60ESR and Chrome 66 (both in ServiceWorker mode, with a recent Wikivoyage ZIM), and did not find any issue.

**Comment by Jaifroid** [comment]
Both of those links point to the Mozilla documentation, with the first one giving the detail about the review process, and it seems to imply that the rejection would apply if it's clear that the HTML is from an external unsanitized source, which isn't the case with our code. We might need to explain to the reviewer...

Regarding the method of copying the html tag's attributes, the issue here is that I can't find any way of accessing or writing to the html element of the iframe's contentDocument (or the contentWindow). Neither outerHTML on the documentElement nor attempts to use createElement and insert it seem to work (see discussion of this in #366). If you have a way of doing it (apart from srcdoc) that I've overlooked, it would be great to try it out.

I'm a bit worried about copying anything in the html element and applying it to the body, so all I've done is copy classes. We could end up adding something that shouldn't be in the body element.

Note that to date we have got by with inserting the full html document into the *body* element of the iframe (which is clearly wrong), so whatever we do here is an improvement. But of course it would be great to optimize this as much as possible.

**Comment by mossroy** [comment]
You're right about the links about extensions. In any case, it's worth proposing the extension and see what they say.
OK I understand for the html/body CSS classes.
It would be worth creating a PR for the https://github.com/kiwix/kiwix-js/tree/InnerHTML-dead-objects-and-history-fix branch, with the UTF-8 and title fix in article.html.
I started testing it and did not find any issue so far.

**Comment by Jaifroid** [comment]
PR superseded by #369

**Pull request closed without merging**
