### PR TITLE
fix issue #604

### PR DESCRIPTION
**Pull request by ykabusalah**
I proposed this solution for fixing issue #604 . Thank you for your time.

### CODE REVIEW

**Comment by ykabusalah** [comment]
This doesn't seem to be an issue with my code, correct?

**Comment by ykabusalah** [comment]
The other pull requests seem to fail for the same reason as this one for the fact that saucelabs is currently down. Are there any updates on that situation?

**Comment by Jaifroid** [comment]
Don't worry, it's because this PR was made from an external repository. What we can do is push a branch from one of our repositories with the identical commits, and that will allow the tests to run. But the code can still be reviewed.

**Comment by ykabusalah** [comment]
Alright. Do I have to do anything for that?

**Pull request closed without merging**
