### PR TITLE
reduced margin between search button and result text

### PR DESCRIPTION
**Pull request by Aditya0049**
solved this issue #1214
Remove unnecessary space below search bar when screen is narrow

### CODE REVIEW

**Comment by Jaifroid** [comment]
@Aditya0049 Thanks for the PR. I'm just running automated tests, then I'll test it myself and get back to you.

**Comment by Jaifroid** [comment]
@Aditya0049 It's looking good, but I think it needs two things:

1. Make the space above the bar equal to the space below it (see screenshot below, where I drew squiggly yellow line);
2. Reduce the size of the search bar and the search button when the screen is narrow (they should be at least the size of the Random button).

You'll see in the CSS some code that reduces the size of the bottom toolbar buttons. We need something similar for the search bar area. You can probably just copy (roughly) the CSS rules. You should ensure that Random button, Search button and search text field are the same height so they match.

I realize there are a few things here that weren't in the original issue, but seeing it after your changes makes the need for them more obvious!

image

**Comment by ehtishama** [comment]
Hi @Aditya0049, I noticed there hasn't been any activity in a while. Are you still working on this issue? If not, I'd like to take on this issue.

**Comment by Aditya0049** [comment]
> Hi @Aditya0049, I noticed there hasn't been any activity in a while. Are you still working on this issue? If not, I'd like to take on this issue.

I'm working ....it'll be done till next 2 days

**Review by Jaifroid — CHANGES_REQUESTED** [review]
See changes mentioned here: https://github.com/kiwix/kiwix-js/pull/1216#issuecomment-1964274103

**Comment by Jaifroid** [comment]
Please feel free to re-open if you want to complete this.

**Pull request closed without merging**
