### PR TITLE
Update changelog for v2.7.0

### PR DESCRIPTION
**Pull request by Jaifroid**
@mossroy Please note suggested new changelog format (proposed to use only for this and future releases) as suggested by @kelson42 in https://github.com/kiwix/kiwix-js-windows/issues/29 

Do you like this?

Milestone closed log is here:
https://github.com/kiwix/kiwix-js/milestone/21?closed=1 
but note a lot of issues there were closed without fixes.

### CODE REVIEW

**Comment by mossroy** [comment]
It's cool.
But you need to add one empty line between each line, else the Markdown renderer puts everything on a single line. See https://github.com/kiwix/kiwix-js/blob/Update-changelog-for-v2.7.0/CHANGELOG.md
The prefix are a bit different in https://github.com/kiwix/kiwix-android/blob/master/CHANGELOG : maybe you could use NEW instead of ENHANCEMENT?
I'm wondering if we should add these prefixes on the previous versions too. It's not crucial.
Maybe you can put today as the 2.7 release date?

**Comment by Jaifroid** [comment]
Happy to make those changes.

**Comment by Jaifroid** [comment]
Bullet points neater than extra line?

image

**Comment by Jaifroid** [comment]
And I just pushed a sample of formatting the previous entry. I suggest we do in the order: NEW, UPDATE, BUGFIX. This means re-ordering some previous entries. (I won't do any more until we've agreed the format.)

**Comment by Jaifroid** [comment]
Also, not sure whether to add fix to "2.6.0 does not run properly on Ubuntu Touch" bug, because I'm not sure we did anything to fix that, or if the platform was updated.

**Comment by mossroy** [comment]
It looks great.
Don't add a line about Ubuntu Touch : we did not change anything

**Comment by Jaifroid** [comment]
I've updated the format as far down as I have been involved in this project (and down to just after the name change to Kiwix JS). Before that, I can probably guess as to what was new and what was an update, but I'm not so familiar, and maybe not necessary to go that far back, or can be left for a future update focusing on documentation?

**Comment by Jaifroid** [comment]
OK, done. I used "most contexts" rather than "some devices", because I think the Chrome extension can be run on more than one device type (e.g., PCs, Macs).

**Comment by mossroy** [comment]
To be precise, I don't think "most contexts" is true.
For now, the main context for kiwix-js (excluding kiwix-js-windows) is Firefox and Chrome browsers extensions. And both are not affected by this enhancement : Firefox extensions do not support SW mode, and Chrome extensions use the built-in browser cache

**Comment by Jaifroid** [comment]
Oh, sorry! I was a bit hasty in merging the commit, but can do a single update as an extra commit to master. I don't think it's about devices, however, which is why I changed it. So I think we can say "some contexts"?

**Comment by mossroy** [comment]
No problem. Yes, "some contexts" seems better IMHO

**Comment by Jaifroid** [comment]
OK, will commit that straight to master.

**Pull request merged**
