### PR TITLE
Added String.prototype.replaceAll method

### PR DESCRIPTION
**Pull request by Greeshmanth1909**
resolves https://github.com/kiwix/kiwix-js/issues/1174
Added String.prototype.replaceAll method in case a browser doesn't support it by default.
Here are the tests I performed:
- Ran `npm run serve`
- Ran `npm run preview`
- Tested with `npm test`
In all the above cases I was able to browse and open zim files in both serviceWorker and JQuery modes in Chrome, Firefox (only JQuery) and Brave. I could't test the magnet link generation for older browsers.
- Tested the extension for Firefox.
- Tested the extension for Chrome in both JQuery and ServiceWorker modes.

### CODE REVIEW

**Comment by Jaifroid** [comment]
@Greeshmanth1909 Thank you! I'll test this on a Chrome < 85 and Firefox < 77 with the download library.

**Comment by Jaifroid** [comment]
I should get to this this weekend.

**Comment by Greeshmanth1909** [comment]
Pushed the code for a completely different issue to this pr by accident. Will fix it asap.

**Review by Jaifroid — CHANGES_REQUESTED** [review]
Thanks very much for this PR. I tested it in Firefox Portable ESR 70.1, and unfortunately it doesn't appear to be working as intended. I get the error `magnetLink.replaceAll is not a function` when clicking on the "Download" link in the library. See screenshot below. Perhaps you haven't injected the function into the correct context? The library code runs in an iframe,

image

**Comment by Jaifroid** [comment]
You can get different versions of Firefox Portable here: https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./

**Comment by Greeshmanth1909** [comment]
Ill try fixing it. Thanks for the resource.

**Comment by Jaifroid** [comment]
I was thinking you might run into CORS issues attempting to inject this function into the library iframe. In fact you almost definitely will, unless there is a known way to polyfill browser functions in a way that works also in iframes with third-party content. It seems unlikely, as it would be considered a vector for attack.

Given this, the only solution -- I think -- would be to make a PR (or suggest a PR) over at kiwix-tools (https://github.com/kiwix/kiwix-tools). I'm sorry if the issue misled you here, I only realized this might be an issue after polyfilling the function in `init.js` appears to have failed.

**Comment by Greeshmanth1909** [comment]
I've also tried defining the polyfill in an inline script of `library.html` it didn't work.

**Comment by Greeshmanth1909** [comment]
Shall I close this pr? @Jaifroid

**Pull request closed without merging**
