### PR TITLE
Update changelog for version 2.6.0

### PR DESCRIPTION
**Pull request by mossroy**

### CODE REVIEW

**Comment by mossroy** [comment]
Note that I did not write the release date yet

**Comment by Jaifroid** [comment]
I wonder if we should add a note to the changelog to say that users will need to search manually for the links on the Wikivoyage landing page until a new Wikivoyage is released? I know it's a bit specific, but might be helpful to users upgrading their apps?

**Comment by mossroy** [comment]
I've updated the changelog for that

**Comment by Jaifroid** [comment]
Looks good, thanks!

**Comment by mossroy** [comment]
I rephrased for the 2019-06 wikivoyage ZIM files, to say that it's fixed in 2019-07 ZIM files.
Now I think we're ready to rebase/squash/merge this PR and start the release

**Pull request merged**
