### PR TITLE
Dummy change to test codedoc (do not merge)

### PR DESCRIPTION
**Pull request by mossroy**

### CODE REVIEW

**Comment by kelson42** [comment]
I think you need to configure codecov. Have a look to https://github.com/openzim/mwoffliner/pull/785.

**Comment by kelson42** [comment]
I think at least one problem is probably that you do not run the automated tests in a way to gather code coverage numbers. These numbers will be then indgested by codecov.io.

**Comment by mossroy** [comment]
Yes, that's what I meant in https://github.com/kiwix/kiwix-js/issues/528#issuecomment-511186036.
And I don't see an easy way to gather these numbers : it does not seem to be an officially supported tests architecture

**Comment by mossroy** [comment]
I'm closing this PR as it would involve much more work to have reports to publish to codecov

**Pull request closed without merging**
