### PR TITLE
changed title of page according to the title of the ZIM

### PR DESCRIPTION
**Pull request by vasusharma7**
Please check the changes. Now the title of the page changes according to the ZIM file viewed by the user...This is illustration of  the issue -The window title should be set to the article title (coming from the iframe) (#280)

### CODE REVIEW

**Comment by vasusharma7** [comment]
Ok. Thanks Mossroy . I am onto it. Will work and get back soon.

**Comment by mossroy** [comment]
Hi @vasusharma7 , are you still willing to work on this PR or should we close it?

**Comment by vasusharma7** [comment]
Yes, I will work on it soon. Please don't close it.

**Comment by mossroy** [comment]
@vasusharma7 : are you still willing to work on this?

**Comment by mossroy** [comment]
@vasusharma7 : I'm closing this inactive PR.
It might be re-opened if necessary

**Pull request closed without merging**
