### PR TITLE
replaced all .innerHTML with .textContent

### PR DESCRIPTION
**Pull request by me-aashish**
As stated in the issue, all the places where .innerHTML was used is now replaced with .textContent keeping the functionalities intact (only contents of app.js were changed, I will also update uiUtil.js once this PR is correct).

### CODE REVIEW

**Comment by Jaifroid** [comment]
@me-aashish You don't appear to have tested this in jQuery mode! See screenshot.

image

**Review by Jaifroid — CHANGES_REQUESTED** [review]
I'm afraid this PR is not working as intended. See screenshot I attached to previous comment. Please test fully as described in CONTRIBUTING before asking for review! Testing fully involves testing in both modes and in more than one browser. Please explain precisely the tests you did when you ask for review.

**Comment by me-aashish** [comment]
Oh! Ok. Working on this ....

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Jaifroid** [comment]
I don't think this approach is going to work, and we should close this PR. If anyone disagrees, please re-open.

**Pull request closed without merging**
