### PR TITLE
innerHTML replaced with textContent

### PR DESCRIPTION
**Pull request by prsndp**
In app.js and uiUtil.js innerHTML replaced with textContent 
issue #824

### CODE REVIEW

**Comment by prsndp** [comment]
> @prsndp Please list the tests you have done on your code, and in which browsers.
Hey, @Jaifroid I tried a lot I'm getting errors during running the npm test command.
Do we have any discussion forum for getting some help? If yes please add me there or give me the link.

**Review by mossroy — CHANGES_REQUESTED** [review]
Thanks for trying to contribute, but please do not ask for a review if you did not test successfully by yourself first.
It's among the reasons I asked to read CONTRIBUTING.md

What is needed here is not a simple search&replace in the code.
You also have to check if some HTML is to be injected in the DOM where we use `.innerHTML`, and find a way to have the same result without `.innerHTML`.
It should be possible to create DOM nodes instead.
For example, for the `base` HTML tag, you can be inspired by https://stackoverflow.com/questions/34317038/adding-base-tag-href-with-javascript-doesnt-work

**Comment by Jaifroid** [comment]
> Hey, @Jaifroid I tried a lot I'm getting errors during running the npm test command.
> Do we have any discussion forum for getting some help? If yes please add me there or give me the link.

If you look at the CONTRIBUTING.md file that mossroy linked in the issue, you will see that a) it tells you how to set up testing (manually in a browser, which is essential, and also the automated testing using `npm test`), and that there is also a link to the Kiwix Slack forum. However, specific questions relating to this PR are best posted here.

**Comment by mossroy** [comment]
@prsndp : are you still willing to work on this PR?

**Comment by mossroy** [comment]
I'm closing this PR as we have no answer from its author.
Feel free to re-open it if necessary

**Pull request closed without merging**
